install.packages('devtools')
library(devtools)
install_version('dplyr', '1.0.2', 'http://cran.us.r-project.org')
install_version('DT', '0.15', 'http://cran.us.r-project.org')
install_version('flexdashboard', '0.5.2', 'http://cran.us.r-project.org')
install_version('htmltools', '0.5.0', 'http://cran.us.r-project.org')
install_version('knitr', '1.30', 'http://cran.us.r-project.org')
install_version('ngram', '3.0.4', 'http://cran.us.r-project.org')
install_version('purrr', '0.3.4', 'http://cran.us.r-project.org')
install_version('shiny', '1.5.0', 'http://cran.us.r-project.org')
install_version('stringr', '1.4.0', 'http://cran.us.r-project.org')
install_version('tidyr', '1.1.2', 'http://cran.us.r-project.org')
